apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-all-global
subjects:
- kind: User
  name: employee 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: all-reader
  apiGroup: rbac.authorization.k8s.io